### ISSUE TITLE
[1.12.2] [0.11.0] Version Match

### ISSUE THREAD

**Issue by GWSheridan** [kenijey/harshencastle#110]
Versions
minecraft 1.12.2
harshencastle-0.11.0
forge-14.23.0.2512

The mod cant run on 1.12.2 even though states in needs 1.12.2

[https://gyazo.com/73cc5ea644d89c7b7f3f2a1aad6589c0](url)

**Comment by Wyn-Price** [comment]
I literally fixed this past night. Ill release a new version in about an hour :)

**Comment by Wyn-Price** [comment]
Ok that took a little longer to finish up, I've uploaded the version to curseforge but it'll be like 30-60 minutes till it goes public
