### ISSUE TITLE
[1.12.1] Update nag

### ISSUE THREAD

**Issue by b0bst3r** [kenijey/harshencastle#112]
Harshencastle-0.12.0.jar nags on login that there's an update which I can't use because it's for 1.12.2 only.

Can we have a config option please to turn this nag off?

[Harshen Castle] The Mod is out of date. Your version 0.12.0, target version: 0.13.1. Click here to go to page

**Comment by Wyn-Price** [comment]
What version are you playing on ?

**Comment by Wyn-Price** [comment]
Also the latest version for 1.12.x isnt 0.12.0 it'd 0.12.1. I don't know why its telling you to download 0.13.0 but I'll definitely look into it today. Unfortunately I've changed alot of the code, and I didn't branch on GitHub (big mistake) so I'll see if I can scavenge the old 0.12.0 code and update it, but I can't promise anything. Thr latest versions are tracked here http://www.wynprice.com/moddedUpdateCheckers/harshencastle.json

**Comment by kenijey** [comment]
He is playing hc1.12.0 on mc 1.12.1

**Comment by Wyn-Price** [comment]
Ah yeh I didnt see that.
I can download the 0.12.0 code through maven, as my API was created then. I'll be able to fix this issue when I get home tonight.
