### ISSUE TITLE
End dim has more spirits then endermen, see picture.

### ISSUE THREAD

**Issue by ProsperCraft** [kenijey/harshencastle#113]
![2018-01-24_13 26 23](https://user-images.githubusercontent.com/4427684/35390476-dca0c156-0198-11e8-8a4e-26b6a04a0590.png)

Is there a way to blacklist them from the end?

**Comment by Wyn-Price** [comment]
Yeh I'll work on that. They shouldn't really be spawning in the end

**Comment by ProsperCraft** [comment]
They appear in the overworld as well, are they supposed to be there too?

**Comment by kenijey** [comment]
which forge versioun u using

**Comment by ProsperCraft** [comment]
forge-1.12.2-14.23.1.2601-universal

**Comment by kenijey** [comment]
yeah i knew that. we were working on forge 2555 i think thats why

**Comment by kenijey** [comment]
even not 2555, 2512

**Comment by ProsperCraft** [comment]
Can you please update?

**Comment by kenijey** [comment]
will try to fix it now. sorry for latency

**Comment by kenijey** [comment]
"They appear in the overworld as well, are they supposed to be there too?"
and yeah, they should be, but rare.
