### ISSUE TITLE
Xray Pendant crashes & corrupts the player, unable to get into the world

### ISSUE THREAD

**Issue by saderen** [kenijey/harshencastle#116]
Hello,

I'm using a modpack called "Hexxit Updated" and there are few mods so I dont think the mods are a problem.
The problem that I had was that whenever I equipped the pendant (with & without entering oreID) it crashed the game.

I am sure this is it because I removed the NBT tag with an editor and it works fine now.

**Comment by Wyn-Price** [comment]
can you send the crash log?

**Comment by saderen** [comment]
Yes of course, right here.

[crash-2018-05-01_17.48.47-server.txt](https://github.com/kenijey/harshencastle/files/1964323/crash-2018-05-01_17.48.47-server.txt)

**Comment by kenijey** [comment]
please tell if it happens again.
