### ISSUE TITLE
Game Crashes When Go To Castle

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#117]
[crash-2018-05-01_21.31.57-server.txt](https://github.com/kenijey/harshencastle/files/1964819/crash-2018-05-01_21.31.57-server.txt)
dunno why...

**Comment by xenxero1** [comment]
It's an issue with the decay check on the dead pontus leaves that are on the castle. When the castle was loaded, it likely tried to run the check on that tick, but threw an exception when it couldn't find it. It could be that one of the leaves is missing that function in the code, or it might just be a fluke issue. Try re-entering the world and see if it crashes again.

**Comment by kenijey** [comment]
yes i know that, but i don't know how can i fix decay check in its class. you know how to?

**Comment by Wyn-Price** [comment]
You'll need to add the decay property to the leave class. Its fine if we do that, it can just be set to forever false

**Comment by xenxero1** [comment]
If you aren't able to solve the issue, I can look at this later tonight and get it working.

**Comment by kenijey** [comment]
it'd be funny :)

**Comment by kenijey** [comment]
can anyone help me on this?
