### ISSUE TITLE
No Sound For Blood Collector

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#14]
it doesn't play when collect or place

**Comment by Wyn-Price** [comment]
Are you sure you have block sound on because it plays when i use it

**Comment by kenijey** [comment]
i did some tests, it ONLY plays if i place blood on soul sand. why i can place blood only on soul sand? i should be able to place it anywhere i want

**Comment by kenijey** [comment]
and no sound if i collect it from soul sand..

**Comment by kenijey** [comment]
oh wait, theres 3/50 blood in my blood collector but i can't place blood on soul sand. i think there is a bug

**Comment by kenijey** [comment]
it's completely confusing. everytime i close my world then reopen or create new world, placement or collecting won't work. or i can't place blood on ground.. it's weird.

**Comment by kenijey** [comment]
okay i found the bug, blood placement requires 3x blood. but sound bug still happens sometimes.
and plz make your tests in survival mode

**Comment by kenijey** [comment]
and another thing, i can't place blood if i have 3/50 blood in my BC. i think it's about #16 .
