### ISSUE TITLE
Accessory

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#18]
**ACCESSORIES:**
6-Telering
-if worn, player can teleport in a 4 blocks range with empty hand-right click.(no shift press)

**Comment by Wyn-Price** [comment]
i tried to do this again and it still seems impossible to do. Ive tried 3 times to do it now and I think well just have to stick to the current system

**Comment by Wyn-Price** [comment]
never mind im smart

**Comment by kenijey** [comment]
i know it, its why i wanted it 3 times xD

**Comment by kenijey** [comment]
updated.

**Comment by kenijey** [comment]
updated. new items

**Comment by kenijey** [comment]
updated again.

**Comment by kenijey** [comment]
we did it. we are awesome. :D
