### ISSUE TITLE
soul part tweaks

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#3]
-need to delete laugh sound if possible
-need to make it pass through walls
-need to make it attacks to the player 
-its spawner will spawn 3-6 (randomly) soul parts

**Comment by Wyn-Price** [comment]
It moves towards the player but doesn't attack. I can fix

**Comment by kenijey** [comment]
it will not attack directly to the player like zombie,
fly around...attack...fly around...attack...

**Comment by Wyn-Price** [comment]
Alright I'll work on the AI when I get home

**Comment by Wyn-Price** [comment]
done ?
