### ISSUE TITLE
Where's Netherrack

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#32]
lol. it's weird
![asadas](https://user-images.githubusercontent.com/24831406/29726100-37719d92-89d7-11e7-9614-81e28894c460.PNG)
all other recipes works fine

**Comment by Wyn-Price** [comment]
![image](https://user-images.githubusercontent.com/15876682/29731067-eb09d240-89da-11e7-9f4f-f67f1afcf7bf.png)
??

**Comment by kenijey** [comment]
i still dont understand how the hell is mine not working

**Comment by kenijey** [comment]
nvm it works now but sometimes not. its weird..

**Comment by Wyn-Price** [comment]
I'll try to replicate it but if I can't then idk why it's happening

**Comment by kenijey** [comment]
nvm it, plz see other issues

**Comment by Wyn-Price** [comment]
I'm not at my PC at the moment but I will be in about an hour where I'll fix them

**Comment by kenijey** [comment]
k
