### ISSUE TITLE
Cauldron Doesn't Empty The Fluid Bucket That I Fill It With

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#38]
put heretic cauldron(empty)
get any fluid bucket that cauldron is fillable with it
right click (survival or creative) boom, u filled the cauldron but u still have that fluid bucket

**Comment by Wyn-Price** [comment]
yeh i forgot to sync it, its fixed now

**Comment by kenijey** [comment]
oh ok

**Comment by kenijey** [comment]
lol there is a glitch, it empties the fluid buckets from vanilla in creative mode.

**Comment by kenijey** [comment]
oh no it's a bug, it doesn't empties harshen castle fluid buckets, never.

**Comment by Wyn-Price** [comment]
fixed again just forgot to sync
