### ISSUE TITLE
Lightning Ritual Improvement/Enhancement

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#42]
When the player places all ritual pedestals correctly, the texture that i made and pushed will be placed under the pedestals and the middle texture will be placed just like blood block at the middle. is it possible?

the textures will be shown at the zero level of the pedestals. 

i can explain more if u dont get

**Comment by kenijey** [comment]
for example, if the player puts the 4. pedestal to the correct place, in this picture i put blood block for example but the correct texture is this that at the middle:
![middle](https://user-images.githubusercontent.com/24831406/29749075-e9793f1c-8b2c-11e7-852f-b05fd31a1d77.png)

**Comment by kenijey** [comment]
i make this to let the player make sure he built the ritual design correctly. and make it cooler.

**Comment by Wyn-Price** [comment]
not exactly. I can make it so a particle appeares above the cauldron and moves into the middle but doing it this way would involve custom rendering

**Comment by kenijey** [comment]
not cauldron, the pedestal ritual that 4x pedestals i mean. i can draw a picture if u want

**Comment by kenijey** [comment]
and it needs a sound while its happening. i will push a sound tomorrow for it

**Comment by kenijey** [comment]
ok no need for it anymore
