### ISSUE TITLE
New Ritual

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#43]
![2017-08-27_13 48 16](https://user-images.githubusercontent.com/24831406/29749141-68f784aa-8b2e-11e7-9aaf-0635e1d835f1.png)
hope it's possible...
the cauldron will be filled with different fluids in the ritual. ill add different recipes in future. sometimes blood, sometimes water... etc
i put stones to make it clearer, they aren't effective. only the pedestals, cauldron and blood

**Comment by kenijey** [comment]
ritual time should be about 30 seconds. it has 2 phases.
in first phase, the items put on the pedestals will be act each other then disappear,(electricity effects from pedestals to cauldron) and an item will be spawned on the cauldrons top. (item slot)
in second phase, just like a normal cauldron ritual. the item that spawned on the top of the cauldron will down in the liquid and then consume the liquid and go up back the new item, thats all. 
NOTE: the item that spawned before cauldron and after the cauldron is same. no different item after consuming the liquid in the cauldron.

**Comment by kenijey** [comment]
and i can help about effects xD

**Comment by Wyn-Price** [comment]
It is possible and I'll do it after I finish the armour

**Comment by kenijey** [comment]
thats awesome to hear

**Comment by kenijey** [comment]
it says ritual built wrong when i put apples into pedestals and gold block on heretic cauldron then harshing water in cauldron and shuffle it with heretic stick

**Comment by kenijey** [comment]
lol, the inverse. my stupid

**Comment by kenijey** [comment]
uhm, but it never changes the item. is it ready to work?

**Comment by Wyn-Price** [comment]
It works for me, are you sure you out the right liquid in the cauldron
