### ISSUE TITLE
Blood Block Bug & Config

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#48]
![fasd](https://user-images.githubusercontent.com/24831406/29785178-521f28f8-8c2f-11e7-91ed-27dc32e56353.PNG)

**Comment by Wyn-Price** [comment]
I think I fixed that

**Comment by kenijey** [comment]
hey ah, i reproduced this. it happens, but no blood block. it just sets some block around to air, no blood placement.

**Comment by kenijey** [comment]
experiment:i put a villager and fences around, started hitting him and some of the fences got disappear
