### ISSUE TITLE
KUANTA System

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#49]
**Unstable Kuantic Element Ore** (i will add this as a block)
-drops 1-3 Kuantic Dust
-spawns as single block in underground, height level 0 between 16, spawn chance 2x more than soul ore
-when you look to it first time, it will display its first texture. then you look another way (get the block out of the screen u have) it will turn its second texture, (can be understandbetter with qCraft mod)

**Kuantic Dust**
it's an item to craft Kuanta Emergence

Kuanta Emergence
it's the hardest part. with this item, you can craft this with this recipe:

"   ",
"aka",
"   ",
k=kuanta emergence
a=ANY BLOCK. 
yes, any block, all blocks in the game that registered. and result is 1 block: Kuanta Block.  and the texture is that changes between that 2 blocks in every 3 seconds. and a green effect on the item texture while changing. 
lets come to the hardest part, what happens when u put that block.
when u put it, the first block u put in the recipe it will be. then you look other way then look to block back, boom! it turned to the second block. AND, both blocks should be working as well. LET me give an example for this thing.

i put crafting table, kuanta emergence, and enchantment table on the crafting. then the result is Kuanta Block(with green colored name). i got that block, its texture is crafting table, and 3 seconds passed, its enchantment table now. and so on.. i put that block on the ground. i'm looking at it, it's crafting table. right clicked, crafted something as a normal crafting table. then i turn my back, i mean i look just another way that get off the block from my screen. then i turn my front back, boom! it's an enchanting table! i put an item and lapis lazuli then enchanted something, then turn my back and front again, it's crafting table.

i have many more ideas that are really cool with it, but i need to see these things can be coded.. i hope

**Comment by Wyn-Price** [comment]
impossible

**Comment by kenijey** [comment]
lol. its really sad, but true xD ...
