### ISSUE TITLE
Bloody Ritual on Pedestal Slab - Status: Need Recipe Work (example)

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#5]
why here, because of the picture
![2017-07-22_14 23 25](https://user-images.githubusercontent.com/24831406/28490702-63ba18ce-6ee9-11e7-8348-c95a19e9de4c.png)

3x3x1 soul sand, blood around and cauldron at the middle

problems:
-player cant place blood block (need blade or shift+right click blood collector?) yet
-...

**Comment by kenijey** [comment]
or maybe NOT cauldron, new block called pedestal slab. going to add it. will make a new block model..

**Comment by Wyn-Price** [comment]
So you want blood to be able to be placed by shift clicking with the blood collector?

**Comment by kenijey** [comment]
i mean i ask should it be like that
updated image in issue.

**Comment by Wyn-Price** [comment]
blood collector now places blood

**Comment by Wyn-Price** [comment]
just reliased you wanted a ritual as well

**Comment by kenijey** [comment]
problem is blood disappears as it should, but how to make this ritual?
maybe a solution: increase the blood block disappear time for %30 ?

**Comment by kenijey** [comment]
and it disappears on soul sand (i think all sands) very fast
i think need to increase the time needed for it despawn by about %100

**Comment by kenijey** [comment]
ok i fixed blood block despawn thing
now need you for adding recipe for this new ritual

**Comment by kenijey** [comment]
and ah, the ritual is simple. you just put an item (1x) on the pedestal slab and thats all. effect should look like consuming the bloods around/ground (red particle effects maybe). and the item will be changed on the pedestal.
