### ISSUE TITLE
Shrine Loot Chest

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#58]
while travelling on superflat world
[crash-2017-09-01_11.00.44-server.txt](https://github.com/kenijey/harshencastle/files/1269563/crash-2017-09-01_11.00.44-server.txt)

**Comment by Wyn-Price** [comment]
This is saying that the world at the time was null. Does this happen Everytime

**Comment by kenijey** [comment]
i dont know i didnt play too much

**Comment by Wyn-Price** [comment]
Ok

**Comment by Wyn-Price** [comment]
couldnt find an issue
