### ISSUE TITLE
Health++ Dupe Bug Still Happens

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#59]
wear criminal pendant, close gui, open gui again, unwear it, then wear elemental pendant, close gui, you have all their properties (health increased 4 hearts, criminal pendant property still i have)

**Comment by Wyn-Price** [comment]
Add the onRemove to the criminal pendant (look in the ElementalPendant class for how to)

**Comment by kenijey** [comment]
oh thx
