### ISSUE TITLE
Lightning Ritual things

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#63]
gold blocks

**Comment by Wyn-Price** [comment]
I haven't made it check to see if it's gold yet

**Comment by Wyn-Price** [comment]
I'll look into it

**Comment by kenijey** [comment]
maybe you want to close this issue? :D

**Comment by Wyn-Price** [comment]
I have made it so the block has to be gold blocks yet I'll do that now

**Comment by kenijey** [comment]
im closing it by assuming ur completely done it
