### ISSUE TITLE
A New Item: Iron Bow

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#64]
-repairable on anvil by an iron ingot

**Comment by kenijey** [comment]
ok i completed it but it's not repairable by iron ingot on anvil. is it possible?

**Comment by kenijey** [comment]
ok its repairable by itself. nvm this shit

**Comment by Wyn-Price** [comment]
i can make it like this if you want

**Comment by kenijey** [comment]
what? repairing with iron ingot? yeah that would be helpful
