### ISSUE TITLE
Can't Fill Empty Glass Container With Milk By Right Clicking to Cow

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#66]

**Comment by Wyn-Price** [comment]
I havnt implimented this yet ill do that when I get home

**Comment by kenijey** [comment]
and this easy thing

**Comment by Wyn-Price** [comment]
none of what you did made sense. You put a function for the entity class into the item

**Comment by Wyn-Price** [comment]
i already fixed this ?

**Comment by kenijey** [comment]
lol so sorry my stupid
