### ISSUE TITLE
All Glass Container Types Should Be Stackable Up To 16

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#67]

**Comment by Wyn-Price** [comment]
idk i think that it kinda fits them to be stackable to only 1. Its like a potion

**Comment by kenijey** [comment]
at least empty container

**Comment by Wyn-Price** [comment]
that would mean making a new item for the empty glass container, as all items with the same meta data have to have the same stacksize, as its regitered per item not itemstack

**Comment by kenijey** [comment]
hmm ok
