### ISSUE TITLE
Feature request- add a config file - able to disable blood.

### ISSUE THREAD

**Issue by ProsperCraft** [kenijey/harshencastle#71]
I would like to add your mod, but I can't have the blood in the pack.

Please add a config file, and in that config file add the ability to turn off blood splats on the ground.

**Comment by Wyn-Price** [comment]
I'll add the config for it later today.
One problem, alot if the rituals in the mod require blood to be used, you can make blood from the blood factory but it's nowhere near as efficient

**Comment by Wyn-Price** [comment]
In fact I'll add a config for.if the blood should be used in the rituals, but you'll still have blood in the cauldron

**Comment by ProsperCraft** [comment]
I just don't want blood splatters all over the ground, not super kid friendly :)

Perhaps we could hold a vial in our offhand and it gets filled when killing mobs?

**Comment by kenijey** [comment]
that makes sense.

**Comment by Wyn-Price** [comment]
new thing is at #74
