### ISSUE TITLE
Inventory items shifting/changing slots when accessories tab is open

### ISSUE THREAD

**Issue by DingoX3** [kenijey/harshencastle#72]
GIF of whats happening---> https://imgur.com/a/uteTU

MC version: 1.12.1
Harshen Castle: 0.9.0
Forge: 2469

**Comment by Wyn-Price** [comment]
I think I know what's causing this. I'll fix it when it get home from school later today

**Comment by Wyn-Price** [comment]
ok im gonna need some info. are you playing on a server or multiplayer?

**Comment by Wyn-Price** [comment]
can you post the full fml-client-latest.log to pastebin then send me the result. because through testing, we (me and the other developer) both got this.
![imageInventory](https://user-images.githubusercontent.com/15876682/30124770-2fe1d73a-932e-11e7-9c4c-8035c56d4bbb.gif)

**Comment by ProsperCraft** [comment]
[TownCraft-.04.zip](https://github.com/kenijey/harshencastle/files/1282570/TownCraft-.04.zip)

There is a twitch profile, click new custom profile, click on the nearly invisible import word, and import this profile then you can join the server and see first hand :)

**Comment by kenijey** [comment]
so its not on our side

**Comment by ProsperCraft** [comment]
Not on our side?  yes, its a problem still, and it only happens with your mod.

**Comment by DingoX3** [comment]
Theres a conflict here with something. I was hoping you could help us figure out what it was, but i guess we'll just remove it from the pack.

**Comment by Wyn-Price** [comment]
ill look into it now

**Comment by Wyn-Price** [comment]
somone please explain what i do with this zip file

**Comment by Wyn-Price** [comment]
want nvm

**Comment by ProsperCraft** [comment]
you open the Twitch launcher - https://app.twitch.tv/download

Then you click on mods, then minecraft

then you click on Create Custom Profile, then at the top there are nearly invisible letters saying import, click on that, then select that zip file which is a profile export.

This will set up the modpack, the server is already set up, just run and connect to the server to see your mod in action with live players :)

**Comment by Wyn-Price** [comment]
ok thanks

**Comment by Wyn-Price** [comment]
ok it is a problem with servers. Looking into it

**Comment by Wyn-Price** [comment]
ok i believe ive fixed it. debugging more now

**Comment by Wyn-Price** [comment]
the issue was that at first, that section of code wasnt being registered by the server, and i was also trying to send infomation to the server, from the server which resulted in the server trying to make the serverside player a clientside player, which didnt work

**Comment by Wyn-Price** [comment]
the file will be here if when its been [approved](https://minecraft.curseforge.com/projects/harshen-castle/files/2476614)

**Comment by kenijey** [comment]
hey ah, i'm playing my modpack called [ezteria](https://github.com/kenijey/Ezteria) and im experiencing this bug **without** harshen castle. how weird. i think it is a bug about inventory tweaks or something. harshen castle is not installed in my modpack but items are moving randomly in my inventory.

**Comment by Wyn-Price** [comment]
@kenijey this was an issue with harshencaste. The container wasn't being opened on the server side and it meant the that the players inventory was locked (this is a thing put in place my Mojang in vanilla minecraft to prevent hacked clients being able to add items.). I've fixed it now don't worry

**Comment by kenijey** [comment]
hmm but me and my friend experiencing the same problem. i think another mod is messing things up again

**Comment by Wyn-Price** [comment]
Well it wasn't the case in this issue. Is it just the harshen inventory or all inventories
