### ISSUE TITLE
Soul Shield Activation (keybinding)

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#81]
it needs a keybinding to activate it.
what i mean:
i wear the soul shield, it will not absorb any damage till i press the key and activate it.
and i can deactivate it by pressing the same key.
another thing, when it activated, its texture will look like enchanted. it should work on the screen (accessory gui-right place of the hotbar)

and dont change it to soul thing, it should absorb all damages, thats cool

**Comment by kenijey** [comment]
and ah, 1 more thing if possible, it would be very cool. when the pendant activated, an effect on the player body same like enchanted.

**Comment by Wyn-Price** [comment]
I'll don't so if it's active, it has the enchanted tint

**Comment by kenijey** [comment]
so can u make a keybinding to activate it?

**Comment by kenijey** [comment]
no need for it.
