### ISSUE TITLE
Big cauldron

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#87]
A Multiblock Cauldron. size starts from 2x2 and ends at 5x5. (i can make 2x2 or 3x3 or 4x4 or 5x5) but height will always be 1.
and now we will need a real ladle, that made from iron, a big ladle to mix that cauldron. 
this cauldron used to mix liquids in it, and take back with a bucket (or whatever u use that supports liquids).
an example:
i crafted Blowing Cauldron base block, then built 2x2 with it, and boom it turned into a big cauldron. 
then i got a water bucket then right clicked the big cauldron, and it filled %25 with bucket. because its 2x2 so theres 4x cauldron blocks and a bucket of water filled 1x cauldron block so 1x cauldron block/4x cauldron blocks = %25.
and after that i got milk bucket and right clicked it again, then mixed it with iron ladle and the fluid turned into Milky Water.

**Comment by Wyn-Price** [comment]
Ok

**Comment by kenijey** [comment]
updated

**Comment by Wyn-Price** [comment]
ill start this now

**Comment by kenijey** [comment]
it shouldn't be in the game, it's totally unneeded.
