### ISSUE TITLE
1.12.1 Heretic Cauldron Duplicates When Broken

### ISSUE THREAD

**Issue by DingoX3** [kenijey/harshencastle#88]
Video gif link to show whats happening. --> https://imgur.com/8dij6e6

MC: 1.12.1
Modpack: Towncraft
Harshen Castle: 0.9.2
Forge: 2474

**Comment by Wyn-Price** [comment]
I fixed this yesterday, but haven't released a version. This only happens if you break it from the top half. I'll add a version checker when I get home are relea a version
