### ISSUE TITLE
Harshed Effect Does Nothing

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#9]

**Comment by Wyn-Price** [comment]
it does if you activate it by drinking the Void container, Ill change it so it does it on the /effect command as well

**Comment by Wyn-Price** [comment]
wait i just released im talking about the wrong effect

**Comment by Wyn-Price** [comment]
it does do things but the effect hurts the player, and while in creative mode it wont do that

**Comment by Wyn-Price** [comment]
wait no i was wrong

**Comment by kenijey** [comment]
i just got into harsing water, and i got harsed effect but nothing happened. it should damage me..

**Comment by Wyn-Price** [comment]
right you do reliase that the damage per second goes like this:
level1->0 damage
level2->2 damage
level3->5 damage

**Comment by kenijey** [comment]
yeah exactly
