### ISSUE TITLE
Ender Bow

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#90]
**Ender Bow**
-its arrow can pass through blocks to hit entities.

**Comment by kenijey** [comment]
did deleted

**Comment by Wyn-Price** [comment]
ok

**Comment by Wyn-Price** [comment]
ive tried for the last 2 hours. Impossible

**Comment by kenijey** [comment]
very sad :( could we figure out a way to damage the mob without the arrow or something? all it needs is this cus, damage the entity with a shot or something
