### ISSUE TITLE
JEI Fluid Improvement

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#94]
if i left click the blood on the cauldron:
![1](https://user-images.githubusercontent.com/24831406/30480885-bd094a74-9a24-11e7-9fb4-c7461f047b96.png)
it should open this page
![2](https://user-images.githubusercontent.com/24831406/30480889-c11238a6-9a24-11e7-8c92-c2ac883e277f.png)

**Comment by kenijey** [comment]
and, if i right click it, it should show where blood used.

**Comment by kenijey** [comment]
it doesnt work

**Comment by Wyn-Price** [comment]
There's no way to add this I've tried. I'll look into it more but I really don't think Ill be able to

**Comment by kenijey** [comment]
lol are u sure most of the mods using this such like thermal expansion or techreborn. fluid on the screen and when right click the fluid u see where it used

**Comment by Wyn-Price** [comment]
Yes that's using fluidstacks, blood isn't actually a fluid so therefore it can't be right clicked to produce how it was made

**Comment by kenijey** [comment]
hmm so make blood a fluid? blood bucket etc

**Comment by Wyn-Price** [comment]
That would mean I would have to redo all of the Rituals and JEI rituals. I'll look into other mods tho

**Comment by kenijey** [comment]
lol ok. but i have a voice in my inside that tells we will need blood as a fluid in future

**Comment by kenijey** [comment]
and uhm, theres some other mods that uses blood as a fluid also. is there a something like bloodFluid in forge oredict? so it will be shared between mods and that makes sense. we also add put blood fluid with blood collector etc, that would be funny

**Comment by Wyn-Price** [comment]
making the blood a fluid isnt a good idea. Im not going to go through and change nearly all of the cauldron code AGAIN just to impliment it. Its fine how it is.

**Comment by kenijey** [comment]
ok

**Comment by Wyn-Price** [comment]
Theres not a way to do it. I can add a tooltip to the hoverover mouse, or a new item that shows the liquids and how to get them
