### ISSUE TITLE
New Insane Crazy Feature

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#95]
this is actually what ive been dreaming for minecraft. it is under the bedrock system.
the question is should it be in the harshen castle or better underground mod..
second question is, is it possible...

**-what the feature is-**
1-we will add a new pickaxe that can mine bedrock.
2-we will add floor generation under the bedrock (its like floor from -1 to -120 around(maybe much more))
3-it will remind the real world's underground, so we have to make a good underground for it. it will replicate how the real earth is.

**Comment by Wyn-Price** [comment]
Pretty much impossible. You could do it as a custom dimension if the player gets lower than a certian point but there's no way to get blocks to generate below 0

**Comment by kenijey** [comment]
hmm.. need to think more about this. it gave me an idea about the bedrock level with the new dimension... 
i think ive found and its very compatible with HC. ill open new issue later
