### ISSUE TITLE
Jewel Dirt

### ISSUE THREAD

**Issue by kenijey** [kenijey/harshencastle#98]
it should spawn on the overworld surface, but **under a grass block**. not directly on the surface.

it should drop min:1 max:2 diamond shards, min:1 max:3 emerald shards (together)

**Comment by Wyn-Price** [comment]
I can make it so it rarely spawns in one in the chaotic or far biome in pontus world

**Comment by kenijey** [comment]
uhm but did you see its texture? i just edit vanilla dirt

**Comment by Wyn-Price** [comment]
So how rare should I make it

**Comment by kenijey** [comment]
not about the rarity. let me tell a different way,
i will make texture for the pontus world version of it, so you will add meta of the block ok?
so the vanilla dirt version(texture) will spawn in overworld, HD dirt version(texture) will spawn in pontus
u can make it same rarity in overworld and pontus

**Comment by Wyn-Price** [comment]
And should it only spawn where normal dirt is ?

**Comment by kenijey** [comment]
uhm in overworld, it should spawn just under a grass block randomly, so add a grass block check then place it under of it, it is possible right?
you can spawn it directly on the surface for pontus world. but it shouldnt be visible in the overworld(dim0)

**Comment by Wyn-Price** [comment]
Yeh I can do that

**Comment by kenijey** [comment]
ok great
uhm, can you make it spawn also at the bottom of the lakes/seas? like clay
cus that makes sense, in real life jewel shards found in streams' dirt base

**Comment by Wyn-Price** [comment]
Yeh ok

**Comment by kenijey** [comment]
and ah theres no jewel dirts in overworld if u did, i searched with xray pendant

**Comment by Wyn-Price** [comment]
It definitely spawns in the overworld. I made it print out the position when it spawns and it does happen, but it's a bit rare
